---
name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy

defaults:
  run:
    shell: nix develop --command bash {0}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cacheID: deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::042049374186:role/github-cathal-dev
          role-duration-seconds: 900

      - name: Show AWS identity
        run: aws sts get-caller-identity

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Sync package
        run: pnpm run sync
